"""
================================================================================
 KYTRON AI CONSULTANT — DATABASE MODELS (ai_models.py)
================================================================================
Complete rebuild — lives at Project-A root per the new file-location
requirement (no consultant/ package). Fresh SQLAlchemy bind
("ai_consultant" -> ai_consultant.db) — not reused from the old
consultant_*.db tables, since this is an architectural replacement, not a
migration.

Kept deliberately small, matching the spec's memory-field list (Section
13): conversation identity/ownership, a compact JSON fact store instead
of a full transcript, and an informational (never routing-locking)
current_topic. No conversation-state "lock" fields exist anywhere in this
file or anywhere else in the new architecture — see ai_consultant.py's
module docstring for why.
================================================================================
"""
import json
from datetime import datetime

from app import db

AI_BIND_KEY = "ai_consultant"


def _now():
    return datetime.utcnow()


class AIConversation(db.Model):
    __bind_key__ = AI_BIND_KEY
    __tablename__ = "ai_conversations"

    id = db.Column(db.Integer, primary_key=True)
    conversation_uid = db.Column(db.String(40), unique=True, nullable=False, index=True)

    # Loose references only — Customer/Project live in the main database,
    # a different physical DB file than this table.
    visitor_token = db.Column(db.String(64), index=True)
    customer_id = db.Column(db.String(20), index=True)

    channel = db.Column(db.String(20), default="visitor", nullable=False)  # visitor | client
    status = db.Column(db.String(20), default="active", nullable=False)     # active | ended

    # Set only after a successful order_id+email (or authenticated
    # customer-owns-it) verification — see ai_security.py. Once set, tool
    # execution scopes EVERY project-data call to this order_id only.
    verified_order_id = db.Column(db.String(32), index=True)
    failed_lookup_attempts = db.Column(db.Integer, default=0, nullable=False)

    # INFORMATIONAL ONLY. Never read by any routing/dispatch decision —
    # see ai_consultant.py. Exists purely so the system prompt can remind
    # the model what was recently being discussed; the model itself
    # decides every turn fresh whether that's still relevant.
    current_topic = db.Column(db.String(200))

    # Structured facts extracted from the conversation (project_type,
    # budget, timeline, features, ...) — a JSON object, not a transcript.
    # Deterministically merged/updated (see ai_memory.py), never fully
    # regenerated by an extra AI call.
    conversation_facts = db.Column(db.Text, default="{}")

    # Compact deterministic summary of older turns once the recent-window
    # cap is exceeded — see ai_context.py. Never a substitute for
    # conversation_facts; this is prose context, facts are structured data.
    rolling_summary = db.Column(db.Text)

    escalated = db.Column(db.Boolean, default=False, nullable=False)
    escalation_reason = db.Column(db.Text)

    title = db.Column(db.String(200))

    created_at = db.Column(db.DateTime, default=_now, nullable=False)
    updated_at = db.Column(db.DateTime, default=_now, onupdate=_now, nullable=False)
    ended_at = db.Column(db.DateTime)

    messages = db.relationship(
        "AIMessage", backref="conversation", lazy="dynamic", order_by="AIMessage.created_at",
    )

    def get_facts(self):
        try:
            return json.loads(self.conversation_facts or "{}")
        except (TypeError, ValueError):
            return {}

    def set_facts(self, facts: dict):
        self.conversation_facts = json.dumps(facts or {})


class AIMessage(db.Model):
    __bind_key__ = AI_BIND_KEY
    __tablename__ = "ai_messages"

    id = db.Column(db.Integer, primary_key=True)
    conversation_id = db.Column(db.Integer, db.ForeignKey("ai_conversations.id"), nullable=False, index=True)

    role = db.Column(db.String(20), nullable=False)  # user | assistant | tool
    content = db.Column(db.Text, nullable=False)

    # Which tool produced this message, if role == "tool". Never used for
    # routing — purely a record for admin/debugging visibility.
    tool_name = db.Column(db.String(60))

    # Where the assistant's reply actually came from: "ai" (a provider
    # answered, tools or not), "option" (zero-AI deterministic option
    # response), "fallback" (every provider unavailable). Never a
    # specific provider name (see ai_prompts.py — never disclosed to
    # the customer; this column is for admin/ops only).
    source = db.Column(db.String(20))

    created_at = db.Column(db.DateTime, default=_now, nullable=False, index=True)


class AIUsageEvent(db.Model):
    """Append-only provider usage/error log — mirrors the previous
    package's usage tracker shape. Powers per-provider cooldown detection
    and admin visibility. provider is a required column so cooldowns are
    genuinely independent per provider (see ai_usage.py)."""
    __bind_key__ = AI_BIND_KEY
    __tablename__ = "ai_usage_events"

    id = db.Column(db.Integer, primary_key=True)
    event_type = db.Column(db.String(30), nullable=False, index=True)
    # call_success | call_error | quota_exceeded | cooldown_skip | provider_fallback
    provider = db.Column(db.String(30), nullable=False, index=True)
    tokens_used = db.Column(db.Integer)
    latency_ms = db.Column(db.Integer)
    tool_calls_count = db.Column(db.Integer)
    error_message = db.Column(db.String(500))
    created_at = db.Column(db.DateTime, default=_now, nullable=False, index=True)


class AISettings(db.Model):
    __bind_key__ = AI_BIND_KEY
    __tablename__ = "ai_settings"

    key = db.Column(db.String(60), primary_key=True)
    value = db.Column(db.Text)
    updated_at = db.Column(db.DateTime, default=_now, onupdate=_now, nullable=False)


def get_ai_setting(key, default=None):
    row = AISettings.query.get(key)
    return row.value if row else default


def set_ai_setting(key, value):
    row = AISettings.query.get(key)
    if row:
        row.value = value
    else:
        row = AISettings(key=key, value=value)
        db.session.add(row)
    db.session.commit()
